CREATE DATABASE INGESOFT;



-- Crear la tabla AREAS
CREATE TABLE AREAS(
    ARE_ID SERIAL NOT NULL,
    ARE_NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ARE_ID)
);

-- Crear la tabla PUESTOS
CREATE TABLE PUESTOS(
    PUE_ID SERIAL NOT NULL,
    PUE_NOMBRE VARCHAR(50) NOT NULL,
    PUE_SUELDO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (PUE_ID)
);

-- Crear la tabla EMPLEADOS
CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRE VARCHAR(50) NOT NULL,
    EMP_DPI VARCHAR(16) NOT NULL UNIQUE,
    EMP_PUESTO INT NOT NULL,
    EMP_EDAD INT NOT NULL,
    EMP_SEXO VARCHAR(10) NOT NULL,
    EMP_AREA INT NOT NULL,
    EMP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_PUESTO) REFERENCES PUESTOS (PUE_ID),
    FOREIGN KEY (EMP_AREA) REFERENCES AREAS (ARE_ID)
);

