CREATE DATABASE INGESOFT;

CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRE VARCHAR(50) NOT NULL,
    EMP_DPI VARCHAR(16) NOT NULL,
    EMP_PUESTO INT NOT NULL,
    EMP_EDAD VARCHAR NOT NULL,
    EMP_SEXO INT NOT NULL,
    EMP_AREA INT NOT NULL,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_PUESTO) REFERENCES PUESTOS (PUE_ID),
    FOREIGN KEY (EMP_AREA) REFERENCES AREAS (ARE_ID)
);

CREATE TABLE PUESTOS(
    PUE_ID SERIAL NOT NULL,
    PUE_NOMBRE VARCHAR(50) NOT NULL,
    PUE_SUELDO VARCHAR NOT NULL,
    PRIMARY KEY (PUE_ID)
);

CREATE TABLE AREAS(
    ARE_ID SERIAL NOT NULL,
    ARE_NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ARE_ID)
);

