--Crear la Basededatos
CREATE DATABASE ingesoft
	IN rootdbs
	WITH LOG


-- Crear la tabla AREAS
CREATE TABLE AREAS(
    ARE_ID SERIAL NOT NULL,
    ARE_NOMBRE VARCHAR(50) NOT NULL,
    PUE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (ARE_ID)
);
SELECT * FROM AREAS;

-- Crear la tabla PUESTOS
CREATE TABLE PUESTOS(
    PUE_ID SERIAL NOT NULL,
    PUE_NOMBRE VARCHAR(50) NOT NULL,
    PUE_SUELDO DECIMAL(10, 2) NOT NULL,
    PUE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (PUE_ID)
);

-- Crear la tabla EMPLEADOS
CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRE VARCHAR(50) NOT NULL,
    EMP_DPI VARCHAR(16) NOT NULL UNIQUE,
    EMP_PUESTO INT NOT NULL,
    EMP_EDAD INT NOT NULL,
    EMP_SEXO VARCHAR(10) NOT NULL,
    EMP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EMP_ID),
    FOREIGN KEY (EMP_PUESTO) REFERENCES PUESTOS (PUE_ID)
);

CREATE TABLE ASIGNACION_AREAS (
    ASI_ID SERIAL PRIMARY KEY,
    ASI_EMP_ID INT NOT NULL,
    ASI_ARE_ID INT NOT NULL,
    ASI_SITUACION SMALLINT DEFAULT 1,
    FOREIGN KEY (ASI_EMP_ID) REFERENCES empleados(EMP_ID),
    FOREIGN KEY (ASI_ARE_ID) REFERENCES areas(ARE_ID)
);

